/* global module */

module.exports = {
    'american': 'Amerikanisch',
    'asian': 'Asiatisch',
    'austrian': 'Österreichisch',
    'auflauf': 'Auflauf',
    'balkan': 'Balkan',
    'bbq': 'Grill',
    'brunch': 'Brunch',
    'burger': 'Sandwich & Burger',
    'cream': 'Sahnig',
    'chocolate': 'Schokolade',
    'chicken': 'Hühnchen',
    'couscous': 'Couscous',
    'dip': 'Dips',
    'drink': 'Getränk',
    'egg': 'Ei',
    'fish': 'Fisch',
    'flammkuchen': 'Flammkuchen',
    'fruity': 'Fruchtig',
    'hurricane': 'Hurricane Glas',
    'indian': 'Indisch',
    'ingredient': 'Zutat',
    'italian': 'Italienisch',
    'leberkas': 'Leberkäse',
    'longdrink': 'Longdrink Glas',
    'mexican': 'Mexikanisch',
    'main': 'Hauptgericht',
    'meat': 'Fleisch',
    'old-fashioned': 'Tumbler',
    'oven': 'Ofen',
    'pan': 'Pfanne',
    'pasta': 'Pasta',
    'pot': 'Topf',
    'potato': 'Kartoffel',
    'pudding': 'Pudding',
    'rice': 'Reis',
    'rum': 'Rum',
    'russian': 'Russisch',
    'salad': 'Salat',
    'sauce': 'Soße',
    'soup': 'Suppe',
    'stew': 'Eintopf',
    'spanish': 'Spanisch',
    'spinach': 'Spinat',
    'side': 'Beilage',
    'sirup': 'Sirup',
    'sweet': 'Süß',
    'vegan': 'Vegan',
    'vegi': 'Vegetarisch',
    'vodka': 'Wodka',
    'whisky': 'Whisky',
    'wineglas': 'Weinglas',
    'wok': 'Wok',
    'wrap': 'Wrap',
};
